"""Machine-readable DSL capability schema."""

from __future__ import annotations

from typing import Any


def dsl_schema() -> dict[str, Any]:
    """Return Intentional's agent-facing DSL capabilities."""
    return {
        "dsl_version": "vnext-draft",
        "top_level_rule_fields": [
            "id", "enabled", "labels", "notes", "while", "after", "stable_for", "hold", "observe", "intent",
            "effect", "authority", "confidence", "reason", "group", "profile",
        ],
        "top_level_document_fields": ["rules", "scenes", "targets", "retention_profiles", "time_windows"],
        "target_policy_fields": [
            "default", "ownership", "dispatch", "allowed_fields", "forbidden_automatic_states",
            "unavailable", "max_retries", "user_authority",
        ],
        "target_ownership": ["managed", "opportunistic", "observe_only"],
        "target_unavailable_policy": ["allow", "skip"],
        "target_dispatch": ["apply", "shadow"],
        "observe_operators": [
            "is", "is_not", "lt", "lte", "gt", "gte", "all", "any",
            "not", "none", "changed", "happened", "for", "stable_for",
        ],
        "intent_field_operators": [
            "value", "withdraw", "min", "max", "offset", "multiply", "animate", "generate",
        ],
        "generator_kinds": [
            "sample", "walk", "weighted_sample", "gradient", "noise",
        ],
        "target_metadata": ["ttl", "linger", "transition", "easing"],
        "lifecycle_fields": [
            "while", "after", "stable_for", "hold.while", "hold.until", "hold.until.for",
            "hold.after", "hold.after_when_stops",
            "hold.after.tiers", "hold.after.adjustments", "hold.after.max",
        ],
        "dynamic_hold_after": {
            "aliases": ["hold.after", "hold.after_when_stops"],
            "aliases_are_mutually_exclusive": True,
            "required_exact_fields": ["tiers", "adjustments", "max"],
            "additional_fields": False,
            "tiers": {
                "type": "non_empty_list",
                "max_items": 64,
                "item_required_exact_fields": ["active_for", "duration"],
                "field_types": {"active_for": "duration_string", "duration": "duration_string"},
                "order": "active_for starts at 0s and strictly increases",
                "duration_constraint": "nonnegative",
                "selection": "greatest active_for not exceeding activation lifetime",
            },
            "adjustments": {
                "type": "list",
                "max_items": 64,
                "item_required_exact_fields": ["from", "until", "add"],
                "field_types": {"from": "strict_HH:MM_string", "until": "strict_HH:MM_string", "add": "signed_duration_string"},
                "selection": "first matching item only, in authored order",
                "window": "from inclusive, until exclusive; overnight supported; equal endpoints match all day",
            },
            "max": {"type": "duration_string", "constraint": "positive"},
            "duration_formula": "max(0, min(selected tier duration + selected adjustment add, max))",
        },
        "retention_profiles": {
            "document_field": "retention_profiles",
            "type": "mapping",
            "max_items": 256,
            "name_pattern": "^[A-Za-z][A-Za-z0-9_-]*$",
            "value_type": "hold_mapping",
            "allowed_fields": ["while", "until", "after", "after_when_stops"],
            "additional_fields": False,
            "forbidden_fields": ["use"],
            "reference": {
                "path": "rules[].hold.use",
                "type": "retention_profile_name",
                "must_exist": True,
            },
            "overlay": {
                "local_fields": ["while", "until", "after", "after_when_stops"],
                "semantics": "local fields replace same-named profile fields wholesale",
                "reference_removed_from_effective_rule": True,
                "fingerprint_uses_expanded_rule": True,
            },
            "duplicates": "declaration blocks, names, and nested fields are rejected",
        },
        "time_windows": {
            "document_field": "time_windows",
            "type": "mapping",
            "max_items": 256,
            "name_pattern": "^[A-Za-z][A-Za-z0-9_-]*$",
            "value_required_exact_fields": ["from", "until"],
            "additional_fields": False,
            "field_types": {"from": "strict_HH:MM_string", "until": "strict_HH:MM_string"},
            "boundaries": "from inclusive, until exclusive",
            "overnight_supported": True,
            "equal_endpoints": "match all day",
            "observation_reference": {
                "path": "while|observe|hold.while|hold.until.time_window",
                "required_exactly_one_operator": ["in", "not_in"],
                "value_type": "time_window_name",
                "must_exist": True,
            },
            "adjustment_reference": {
                "path": "hold.after|hold.after_when_stops.adjustments[]",
                "required_exact_fields": ["window", "add"],
                "field_types": {"window": "time_window_name", "add": "signed_duration_string"},
                "must_exist": True,
                "equivalent_inline_fields": ["from", "until", "add"],
                "selection": "first matching adjustment in authored order",
            },
            "duplicates": "declaration blocks, names, and nested fields are rejected",
        },
        "hysteresis": {
            "path": "rules[].while|observe.<entity_id>",
            "container": "the situation must contain exactly one entity and no other clauses",
            "required_exact_fields": ["enter", "exit"],
            "phase_shape": "mapping containing exactly one comparison",
            "operators": ["gt", "gte", "lt", "lte"],
            "value_type": "number_not_boolean",
            "direction": "enter and exit operators must face opposite directions",
            "deadband": "enter and exit thresholds must leave a non-empty deadband",
            "dwell": "top-level after applies only before entry",
            "exit_retention": "hold starts after the exit comparison fires",
            "persistence": "latch and dwell survive restart only while the Rule fingerprint is unchanged",
        },
        "field_withdrawal": {
            "path": "rules[].intent.<target>.<field>.withdraw",
            "wrapper_allowed_fields": ["value", "withdraw", "min", "max", "offset", "multiply", "animate", "generate"],
            "additional_fields": False,
            "values": ["literal_field_value", "adopt", None],
            "null_semantics": "no explicit field withdrawal",
            "adopt_semantics": "restore the normalized actual value captured when the field first became owned",
            "lower_provider_semantics": "reveal the lower-authority provider instead of applying withdrawal",
            "ownership": "a value provider establishes ownership; modifier-only fields do not",
            "persistence": "captured adoption values and pending withdrawals survive restart",
        },
        "shadow_target_policy": {
            "path": "targets.<target>.dispatch",
            "values": ["apply", "shadow"],
            "default": "apply",
            "shadow": {
                "computes": ["would_apply", "would_withdraw"],
                "calls_home_assistant_services": False,
                "creates_applied_plan_state": False,
                "creates_drift_state": False,
                "creates_manual_override_state": False,
                "resuming_apply_reconciles_normally": True,
            },
        },
        "simulation_endpoint": "/api/intentional/simulate",
        "simulation_time_context_field": "timeline[].time_of_day (strict HH:MM)",
        "replay_endpoint": "/api/intentional/replay",
        "simulation_endpoints": ["/api/intentional/simulate", "/api/intentional/replay"],
        "ha_migration": {
            "admin_only": True,
            "read_only_source": True,
            "endpoints": [
                "/api/intentional/migrate-ha",
                "/api/intentional/migrate-ha/{entity_id}",
                "/api/intentional/migrate-ha/propose",
            ],
            "trigger_platforms": ["state", "numeric_state"],
            "action_services": ["light.turn_on", "light.turn_off", "switch.turn_on", "switch.turn_off"],
        },
        "effect_service_policy": "any_home_assistant_domain_service",
        "selector_filters": ["domain", "area", "label", "exclude"],
        "semantic_observations": {
            "purposes": {
                "motion": ["binary_sensor", "motion"],
                "occupancy": ["binary_sensor", "occupancy"],
                "door": ["binary_sensor", "door"],
                "window": ["binary_sensor", "window"],
                "moisture": ["binary_sensor", "moisture"],
                "temperature": ["sensor", "temperature"],
                "illuminance": ["sensor", "illuminance"],
                "power": ["sensor", "power"],
            },
            "authored_filters": ["area", "entity", "device", "exclude"],
            "behavior": ["any", "all", "none"],
            "binary_states": {
                "motion": ["detected", "clear"],
                "occupancy": ["occupied", "clear"],
                "door": ["open", "closed"],
                "window": ["open", "closed"],
                "moisture": ["wet", "dry"],
            },
            "numeric_comparisons": ["above", "below", "is", "is_not", "lt", "lte", "gt", "gte"],
            "edge_field": "changed",
            "power": {
                "domain": "sensor",
                "effective_device_class": "power",
                "operators": ["above", "below", "is", "is_not", "lt", "lte", "gt", "gte"],
                "value_type": "number_not_boolean",
                "comparison_units": "raw native state value; no unit conversion",
                "excluded_device_classes": ["energy", "apparent_power", "reactive_power", "power_factor"],
            },
        },
        "simulation_selector_membership": {
            "field": "selectors",
            "selector_filters": ["domain", "area", "label", "device", "entity", "purpose"],
            "target_field": "targets",
        },
        "simulation_semantic_metadata": {
            "field": "semantic_metadata",
            "record_fields": [
                "entity_id", "area", "device", "device_class", "original_device_class",
            ],
            "required_fields": ["entity_id"],
            "device_class_precedence": ["device_class", "original_device_class"],
        },
        "capabilities": {
            "preview": {
                "endpoint": "/api/intentional/preview",
                "method": "POST",
                "requires_auth": True,
                "mutates_live_engine": False,
                "calls_home_assistant_services": False,
                "horizons_ms": {"type": "ascending_list_of_integers", "max_items": 32, "minimum": 0, "maximum": 86400000},
                "phase_fields": ["horizon_ms", "active_rules", "service_plans", "effects"],
            },
            "diagnostics": {
                "endpoint": "/api/intentional/diagnostics",
                "method": "GET",
                "admin_only": True,
                "query_limit": {"type": "integer", "minimum": 0, "maximum": 500},
                "runtime_event_retention": {"storage": "memory_only", "max_items": 200},
                "service_plan_attempt_retention": {"max_items_per_config_entry": 256},
                "redacted": True,
            },
            "ha_migration": {
                "admin_only": True,
                "read_only_source": True,
                "mutates_or_disables_source": False,
                "max_discovered_automations": 500,
                "max_source_bytes": 256000,
                "max_triggers": 64,
                "max_actions": 64,
                "max_proposal_bytes": 256000,
                "trigger_platforms": ["state", "numeric_state"],
                "action_services": ["light.turn_on", "light.turn_off", "switch.turn_on", "switch.turn_off"],
                "unsupported": ["conditions", "blueprints", "templates", "attribute triggers", "delay", "choose", "wait", "scene", "event"],
                "warnings": ["edge_to_level", "intent_withdrawal"],
            },
            "rollback": {
                "endpoint": "/api/intentional/rules/rollback",
                "method": "POST",
                "admin_only": True,
                "storage_backed_rules_only": True,
                "required_exact_fields": ["generation", "expected_generation"],
                "optimistic_concurrency": True,
                "history_limit": 25,
                "rollback_is_recorded_in_history": True,
            },
        },
    }
